steps:
  -name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/continuous-deployment-practice:$SHORT_SHA', '.']

  -name: 'gcr.io/cloud-builders/docker'
  args: ['push', '-t', 'gcr.io/continuous-deployment-practice:$SHORT_SHA']